### ISSUE TITLE
Add Ad Publishing Privacy Policy type

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/terms-types#10]
Moved from original description: https://github.com/ambanum/OpenTermsArchive/issues/270

**Comment by Ndpnt** [comment]
@MattiSG Is this issue still relevant today?

**Comment by MattiSG** [comment]
Not really. If a new type was to be added, it should go through a GitHub Discussion. This type matches all the conditions for being considered (at least three examples, complete triptych), so it would be fast to go through the process; yet at this stage no one is wanting to add terms of this type, so I guess we'll close that issue and leave it to someone wanting to track such terms to request the addition of this type 🙂
