### ISSUE TITLE
Release fails

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/terms-types#12]
Following #11, [the release fails](https://github.com/OpenTermsArchive/terms-types/actions/runs/4324714057/jobs/7549916684). I indeed had to update the branch protection rules before merging #11, as the names of the mandatory checks had changed from `test / validate` to `validate` and from `changelog / check_changelog / check_changelog` to `check_changelog / check_changelog` (yes, this is all very redundant, I don't understand where those names come from).

The failing step is:

```
Remove 'main' pull request review protection ...
RuntimeError: Response did not return the expected status code from request 'https://api.github.com/repos/OpenTermsArchive/terms-types/branches/main/protection/required_pull_request_reviews'.
Status code: 404 (expected: 200).
```

**Comment by Ndpnt** [comment]
Fixed by updating release bot token and repository's settings.
