### ISSUE TITLE
Support CommonJS

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/terms-types#8]
While wanting to include this package in the contribution-tool, I faced the following issue in the build

https://github.com/OpenTermsArchive/contribution-tool/actions/runs/3936074798/jobs/6732306968

```
    Details:

    /home/runner/work/contribution-tool/contribution-tool/node_modules/@opentermsarchive/terms-types/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { readFile } from 'fs/promises';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

I can't put `type: module` in the project as it creates other problems and it's a problem I've never faced before.

**Comment by MattiSG** [comment]
Thanks for reporting!

You are trying to use the `terms-types` module, which has an [ES Module]() interface, within a CommonJS module.

In JavaScript, there are two different ways to export code:

- ES Modules (ESM): the standard module format introduced in ES6 (ECMAScript 2015). It uses the `import` and `export` keywords to define and use modules.
- CommonJS Modules (CJS): an older module format that uses `require` and `module.exports` to handle modules.

The `terms-types` module is built using the ES Module format. At this stage, we do not intend to expose a CommonJS interface for backwards compatibility.

You can use [import expressions](https://nodejs.org/api/esm.html#import-expressions) in your legacy CommonJS module to dynamically import an ES Module 🙂 See [this StackOverflow answer](https://stackoverflow.com/a/70396888) for a step-by-step guide.

Thank you for your understanding 🙂
